apiVersion: v1
kind: Service
metadata:
  name: shark-svc-prod
  labels:
    app: sharks-app-prod
spec:
  selector:
    app: sharks-app-prod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP