apiVersion: v1
kind: Service
metadata:
  name: shark-svc
  labels:
    app: sharks-app
spec:
  selector:
    app: sharks-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP